### PR TITLE
Automate Unhandled Exception Wiring [Android]

### PR DESCRIPTION
**Pull request by DangMH**
1. Refactors Java Bindings to enable Managed Unhandled Exception event wiring in CrashManager.Register
2. Refactors TraceWriter initializations into CrashManager.Register partial class implementation

@gordallott 
@njpatel 
@Redth

### CODE REVIEW

**Comment by gordallott** [comment]
you should have some protection against people calling .Register() more than once, don't want to be subscribing to events more than once. 

also I know this is from HA but setting .handled = true in the AndroidEnvironment exception handler is bizarre - it blocks any other event handlers from running on that which may or may not be useful, but will probably annoy anyone that wants to use multiple handlers

**Comment by DangMH** [comment]
@gordallott Let me know what you think of the new commits to resolve the two issues you brought up.

**Comment by drungrin** [comment]
I mean non-fatal exception to the application, I need to log it and don't terminate the application.

**Comment by anlinde** [comment]
@drungrin as I said, we currently don't support this but we are working on it.

**Comment by drungrin** [comment]
I think you didn't get the point, I actually use `TraceWriter.WriteTrace(exception, false)` and it works, reporting the exception and not killing the application.

You don't support distinguishing fatal from non-fatal exceptions on the dashboard.

That change 'll break the compatibility.

**Pull request merged**
